# This is a config for E2B sandbox template.
# You can use template ID (cinfyy9ycq1zhq1ozmkv) or template name (aura-test-project) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("aura-test-project") # Sync sandbox
# sandbox = await AsyncSandbox.create("aura-test-project") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('aura-test-project')

team_id = "f73fc8bf-f821-43cb-98a8-b74da2f8038e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "aura-test-project"
template_id = "cinfyy9ycq1zhq1ozmkv"
